export function piTeamsHelp(): string {
	return [
		"pi-crew commands:",
		"",
		"Core:",
		"- Agent can use the `team` tool autonomously; slash commands are manual controls.",
		"- Tool action `recommend` suggests the best team/workflow for a goal.",
		"- /teams — list teams, workflows, agents, recent runs",
		"- /team-run [--team=name] [--workflow=name] [--async] [--worktree] <goal>",
		"- /team-status <runId>",
		"- /team-summary <runId>",
		"- /team-resume <runId>",
		"- /team-cancel <runId>",
		"- /team-retry <runId> [taskId]",
		"",
		"Inspection:",
		"- /team-events <runId>",
		"- /team-artifacts <runId>",
		"- /team-worktrees <runId>",
		"- /team-api <runId> <operation> [taskId=<taskId>] [body=<message>]",
		"- /team-dashboard",
		"- /team-mascot",
		"- /team-transcript <runId> [taskId]",
		"- /team-result <runId> [taskId]",
		"- /team-manager — interactive menu (alias: /team-cleanup-menu)",
		"",
		"Maintenance:",
		"- /team-cleanup <runId> [--force]  (or scope=project/user for uninstall cleanup)",
		"- /team-forget <runId> --confirm [--force]",
		"- /team-prune --keep=20 --confirm",
		"",
		"Portability:",
		"- /team-export <runId>",
		"- /team-import <path-to-run-export.json> [--user]",
		"- /team-imports",
		"",
		"Diagnostics:",
		"- /team-health",
		"- /team-doctor",
		"- /team-init [--copy-builtins] [--overwrite]",
		"- /team-config [key=value] [--unset=key.path] [--project]",
		"- /team-autonomy [status|on|off|manual|suggested|assisted|aggressive] [--prefer-async] [--no-worktree-suggest]",
		"- /team-validate",
		"- /team-help",
		"",
		"Goal loops (P0/P1 — autonomous goal loop):",
		"- team action='goal' config.subAction='start' config.objective='...' config.evaluatorModel='...' [config.maxTurns=20] [budgetTotal=N]",
		"- team action='goal' config.subAction='status' [config.goalId=<id>]",
		"- team action='goal' config.subAction='pause|resume|stop|step|clear' config.goalId=<id>",
		"",
		"Dynamic workflows (P2/P3 — JS-script orchestration):",
		"- Place a .dwf.ts under .crew/workflows/ then: team action='run' workflow='<name>' goal='...'",
		"- team action='workflow-list'",
		"- team action='workflow-get' config.name='<name>'",
		"- team action='workflow-create' confirm=true config.name='<name>' config.script='<.dwf.ts source>'  (USER-initiated only; ACE-gated)",
		"- team action='workflow-save' config.name='<name>' config.script='<source>'",
		"- team action='workflow-delete' confirm=true config.name='<name>'",
		"- /workflows — list dynamic workflows",
		"",
		"Real child workers are enabled by default. Use runtime.mode=scaffold or executeWorkers=false only for dry runs.",
	].join("\n");
}
